### ISSUE TITLE
Correct PR template checklist

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/climate-change-components#10]
`yarn run serve` and `yarn run build:prod` checklist items, probably copied from lab template, do not apply to this library repository. 

Change to:
 - `yarn run lint`
 - `yarn run build:library`
 - `npm pack`
 - `CHANGELOG` updated?
 - version bumped?

**Comment by flibbertigibbet** [comment]
Testing instructions could also be templated to describe how to build and install on the lab project.

**Comment by sharph** [comment]
Should version bumping occur on release instead of per feature?

**Comment by maurizi** [comment]
> Should version bumping occur on release instead of per feature?

This is typically what is done for other projects using a git-flow style release, so I would say yes

**Comment by CloudNiner** [comment]
> Should version bumping occur on release instead of per feature?

👍 to @maurizi 's comment. I've been version bumping on `git flow release`'s
